Repository unb-mds/2024-1-Squad02-CulturaTransparente, pull requests merged in 2024-04, with the labels that each got.

#19 Adicionando arquivo com a Logo do projeto
  documentacoes/Logo - Cultura Transparente.pdf
Labels: documentation, tasks, Front-end

#26 add files
  Front end/projeto-react/.eslintrc.cjs
  Front end/projeto-react/.gitignore
  Front end/projeto-react/README.md
  Front end/projeto-react/index.html
  Front end/projeto-react/package-lock.json
  Front end/projeto-react/package.json
  Front end/projeto-react/src/App.jsx
  Front end/projeto-react/src/imagens/logo-mono2.jpg
  Front end/projeto-react/src/imagens/logo-mono2.png
  Front end/projeto-react/src/index.css
  Front end/projeto-react/src/main.jsx
  Front end/projeto-react/src/styles.jsx
  Front end/projeto-react/vite.config.js
Labels: Front-end

#28 add buttons
  Como rodar
  Front end/projeto-react/package.json
  Front end/projeto-react/src/App.jsx
  Front end/projeto-react/src/imagens/redbox.png
  Front end/projeto-react/src/styles.jsx
  package-lock.json
Labels: Front-end

#34 Adicionei arquivos YML para o workflow do Actions
  .github/workflows/pages.yml
  .github/workflows/super-linter.yml
Labels: enhancement, devops

#39 terminando o git page
  docs/comoexecultar.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#45 Adicionei o prototipo e criei a aba de como contribuir
  docs/contribuir.md
  docs/prototipo.md
  mkdocs.yml
Labels: documentation, enhancement, tasks

#47 Atualizando o readme
  README.md
  documentacoes/logo.png
Labels: documentation, enhancement
